apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: python:3.9-slim 
        envFrom:
        - configMapRef:
            name: python-app-config
        ports:
        - containerPort: 8080
        command: ["python3"] 
        args: ["-m", "http.server", "8080"] 
